/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nexts;

import net.skylix.nexts.terminal.color.Color;
import net.skylix.nexts.terminal.color.ColorNames;
import net.skylix.nexts.terminal.color.ColorSettings;

public class LibraryTest {
    /**
     * This is the main method for the class
     * @param args Arguments that came from the command line interface
     */
    public static void main(String[] args) {
        Color red = new Color(new ColorSettings() {{
            bold = true;
            intense = true;
            underline = true;
            color = ColorNames.RED;
        }});

        System.out.println("This is some example usage: " + args.toString());
        String redText = "This text should be " + red.apply("RED") + ", Cool Right?";

        System.out.println(redText);
    }
}
